# permissions for end users to view imagebuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagebuilder-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pok
    app.kubernetes.io/part-of: pok
    app.kubernetes.io/managed-by: kustomize
  name: imagebuilder-viewer-role
rules:
- apiGroups:
  - pok.kubops.com
  resources:
  - imagebuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pok.kubops.com
  resources:
  - imagebuilders/status
  verbs:
  - get
