---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pok.kubops.com
  resources:
  - imagebuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pok.kubops.com
  resources:
  - imagebuilders/finalizers
  verbs:
  - update
- apiGroups:
  - pok.kubops.com
  resources:
  - imagebuilders/status
  verbs:
  - get
  - patch
  - update
