apiVersion: pok.kubops.com/v1alpha1
kind: ImageBuilder
metadata:
  name: imagebuilder-sample
spec:
  source:
    url: https://github.com/KubOpsCloud/pok.git
  destination:
    image: ghcr.io/KubOpsCloud/pok
  rules:
    - source:
        type: branch
        pattern: main
      build:
        context: .
        file: Dockerfile
        platforms:
          - linux/amd64
      tags:
        - latest
